### PR TITLE
Test describing `phx-trigger-action`

### PR DESCRIPTION
**Pull request by totaltrash**
Here's an example describing the interaction expected for phx-trigger-action, see #47.

I'm not sure how hard implementing this would be (if possible at all)? I'm happy to have a look if you have any pointers!

### CODE REVIEW

**Comment by germsvel** [comment]
Thanks for opening this PR @totaltrash! I think adding support for `phx-trigger-action` would be great. 

If you're up for it, I think we _can_ implement it. We already support submitting a non-LiveView form from a LiveView page, so we _should_ be able to reuse that code to do the actual form submission. 

I think the trickier part is somehow watching for forms with `phx-trigger-action`. We should do the regular `phx-submit` behavior, but when `phx-trigger-action` is set to `true`, we need to then do the non-LiveView form submission.

**Comment by totaltrash** [comment]
Hi @germsvel, this is a pretty naive implementation.

It only triggers on finding the `phx-trigger-action` following a `phx-submit`, but the action could be triggered on any assigns update. It's a bit complicated because `phx-trigger-action` doesn't appear in the DOM until it's set to true (and therefore fired), so it's not something you can look for as an attribute on the form before it's triggered.

**Comment by germsvel** [comment]
Got it. So, we'd have to somehow "watch" the HTML every time it's rendered and see if `phx-trigger-action` is set to `true`. That's a little more complicated, but probably doable. We' have to search the rendered HTML after _any_ type of action, clicks, submits, changes, etc. 

The behavior of `phx-trigger-action` is for the LiveView to disconnect after that and do a full form submit, right? So, once `phx-trigger-action` is set to `true`, we don't want to do anything else on the LiveView. Just submit the form and follow whatever redirect happens from it.

**Comment by totaltrash** [comment]
Yes, you got it.

It may be a little more nuanced - it's a bit of an edge case but what if the updated assigns carrying the `phx-trigger-action` value has other assigns that might change values in the form - do they update before the `phx-trigger-action`?

We'll probably handle the submit as you've already described (using the submit to static form code we already have), but this is available too https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#follow_trigger_action/2

**Comment by germsvel** [comment]
Oh nice. I like [follow_trigger_action/2](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#follow_trigger_action/2). I think we can definitely use that.

**Comment by germsvel** [comment]
@totaltrash I'm going to close this (since this doesn't implement the feature yet) in favor of keeping the discussion in issue https://github.com/germsvel/phoenix_test/issues/47

**Pull request closed without merging**
